#!/usr/bin/env bash

sqlite3 -line ~/Library/Messages/chats.db \
<<-SQL | grep -i -o -e '[[:alnum:]]+ = .+'
    SELECT     MAX(date), h.id, text
    FROM       message AS m
    INNER JOIN handle  AS h
    ON         h.ROWID    = m.handle_id
    WHERE      is_from_me = 0
    GROUP BY   h.ROWID
SQL
